VOCC = [
    [ // 0
        {korean:"사람",  uzbek:"Odam",    type:"Noun"},
        {korean:"집",  uzbek:"Uy",    type:"Noun"},
        {korean:"차",  uzbek:"Avtomobil",    type:"Noun"},
        {korean:"학교",  uzbek:"Maktab",    type:"Noun"}
    ],
    [ // 1
        { korean: "나라", uzbek: "davlat" },
  { korean: "중국", uzbek: "Xitoy" },
  { korean: "일본", uzbek: "Yaponiya" },
  { korean: "미국", uzbek: "AQSH" },
  { korean: "한국", uzbek: "Koreya" },
  { korean: "프랑스", uzbek: "Fransiya" },
  { korean: "독일", uzbek: "Germaniya" },
  { korean: "호주", uzbek: "Avstraliya" },
  { korean: "영국", uzbek: "Angliya" },
  { korean: "빈칸", uzbek: "bo'sh joy" },
  { korean: "알맞다", uzbek: "mos" },
  { korean: "단어", uzbek: "so'z" },
  { korean: "선생님", uzbek: "o'qituvchi" },
  { korean: "학생", uzbek: "o'quvchi" },
  { korean: "의사", uzbek: "doktor" },
  { korean: "회사원", uzbek: "firma ishchisi" },
  { korean: "요리사", uzbek: "oshpaz" },
  { korean: "기자", uzbek: "muxbir" },
  { korean: "가수", uzbek: "qo'shiqchi" },
  { korean: "군인", uzbek: "askar" },
  { korean: "인사말", uzbek: "salomlashish gapi" },
  { korean: "만나다", uzbek: "uchrashmoq" },
  { korean: "반갑다", uzbek: "xursand bo'lmoq" },
  { korean: "한국말", uzbek: "koreys tili" },
  { korean: "그림", uzbek: "surat (chizilgan)" },
  { korean: "이야기하다", uzbek: "suhbatlashmoq" },
  { korean: "저", uzbek: "men/anavi" },
  { korean: "씨", uzbek: "janob/xonim" },
  { korean: "네", uzbek: "ha" },
  { korean: "주부", uzbek: "uy bekasi" },
  { korean: "말하기", uzbek: "gaplashish" },
  { korean: "어느", uzbek: "qaysi" },
  { korean: "캐나다", uzbek: "Kanada" },
  { korean: "국적", uzbek: "millat" },
  { korean: "묻다", uzbek: "so'ramoq" },
  { korean: "인도", uzbek: "Hindiston" },
  { korean: "직업", uzbek: "kasb" },
  { korean: "아니요", uzbek: "yo'q" },
  { korean: "여러분", uzbek: "sizlar/azizlar" },
  { korean: "무엇", uzbek: "nima" },
  { korean: "러시아", uzbek: "Rossiya" },
  { korean: "파키스탄", uzbek: "Pokiston" },
  { korean: "친구", uzbek: "do’st" },
  { korean: "명함", uzbek: "ism karta" },
  { korean: "이름", uzbek: "ism" },
  { korean: "전화번호", uzbek: "telefon raqam" },
  { korean: "영어", uzbek: "ingliz tili" },
  { korean: "블로그", uzbek: "internetdagi blog" },
  { korean: "찾다", uzbek: "qidirmoq" },
  { korean: "과제", uzbek: "topshiriq" },
  { korean: "문화", uzbek: "madaniyat" }
    ],
    [ // 2
        { korean: "나라", uzbek: "davlat" },
        { korean: "중국", uzbek: "Xitoy" },
        { korean: "일본", uzbek: "Yaponiya" },
        { korean: "미국", uzbek: "AQSH" },
        { korean: "한국", uzbek: "Koreya" },
        { korean: "프랑스", uzbek: "Fransiya" },
        { korean: "독일", uzbek: "Germaniya" },
        { korean: "호주", uzbek: "Avstraliya" },
        { korean: "영국", uzbek: "Angliya" },
        { korean: "빈칸", uzbek: "bo'sh joy" },
        { korean: "알맞다", uzbek: "mos" },
        { korean: "단어", uzbek: "so'z" },
        { korean: "선생님", uzbek: "o'qituvchi" },
        { korean: "학생", uzbek: "o'quvchi" },
        { korean: "의사", uzbek: "doktor" },
        { korean: "회사원", uzbek: "firma ishchisi" },
        { korean: "요리사", uzbek: "oshpaz" },
        { korean: "기자", uzbek: "muxbir" },
        { korean: "가수", uzbek: "qo'shiqchi" },
        { korean: "군인", uzbek: "askar" },
        { korean: "인사말", uzbek: "salomlashish gapi" },
        { korean: "만나다", uzbek: "uchrashmoq" },
        { korean: "반갑다", uzbek: "xursand bo'lmoq" },
        { korean: "한국말", uzbek: "koreys tili" },
        { korean: "그림", uzbek: "surat (chizilgan)" },
        { korean: "이야기하다", uzbek: "suhbatlashmoq" },
        { korean: "저", uzbek: "men/anavi" },
        { korean: "씨", uzbek: "janob/xonim" },
        { korean: "네", uzbek: "ha" },
        { korean: "주부", uzbek: "uy bekasi" },
        { korean: "말하기", uzbek: "gaplashish" },
        { korean: "어느", uzbek: "qaysi" },
        { korean: "캐나다", uzbek: "Kanada" },
        { korean: "국적", uzbek: "millat" },
        { korean: "묻다", uzbek: "so'ramoq" },
        { korean: "인도", uzbek: "Hindiston" },
        { korean: "직업", uzbek: "kasb" },
        { korean: "아니요", uzbek: "yo'q" },
        { korean: "여러분", uzbek: "sizlar/azizlar" },
        { korean: "무엇", uzbek: "nima" },
        { korean: "러시아", uzbek: "Rossiya" },
        { korean: "파키스탄", uzbek: "Pokiston" },
        { korean: "친구", uzbek: "do’st" },
        { korean: "명함", uzbek: "ism karta" },
        { korean: "이름", uzbek: "ism" },
        { korean: "전화번호", uzbek: "telefon raqam" },
        { korean: "영어", uzbek: "ingliz tili" },
        { korean: "블로그", uzbek: "internetdagi blog" },
        { korean: "찾다", uzbek: "qidirmoq" },
        { korean: "과제", uzbek: "topshiriq" },
        { korean: "문화", uzbek: "madaniyat" },
        { korean: "책상", uzbek: "parta" },
        { korean: "의자", uzbek: "stul" },
        { korean: "책", uzbek: "kitob" },
        { korean: "공책", uzbek: "daftar" },
        { korean: "볼펜", uzbek: "ruchka" },
        { korean: "연필", uzbek: "qalam" },
        { korean: "가방", uzbek: "sumka" },
        { korean: "지우개", uzbek: "ochirg'ich" },
        { korean: "시계", uzbek: "soat" },
        { korean: "모자", uzbek: "bosh kiyim" },
        { korean: "우산", uzbek: "soyabon" },
        { korean: "신문", uzbek: "gazeta" },
        { korean: "사전", uzbek: "lug'at" },
        { korean: "안경", uzbek: "ko'zoynak" },
        { korean: "휴대폰", uzbek: "telefon" },
        { korean: "남자친구", uzbek: "yigit o'rtoq" },
        { korean: "동전", uzbek: "tanga" },
        { korean: "차", uzbek: "mashina" },
        { korean: "한국어", uzbek: "koreys tili" },
        { korean: "여자 친구", uzbek: "qiz o'rtoq" },
        { korean: "뭐", uzbek: "nima" },
        { korean: "창문", uzbek: "deraza" },
        { korean: "지도", uzbek: "xarita" },
        { korean: "필통", uzbek: "penal/qalamdon" },
        { korean: "전자사전", uzbek: "elektron lug'at" },
        { korean: "한국어로", uzbek: "koreys tilida" },
        { korean: "자", uzbek: "chizg'ich" },
        { korean: "잡지", uzbek: "jurnal" },
        { korean: "지갑", uzbek: "hamyon" },
        { korean: "여기 있어요", uzbek: "marhamat" },
        { korean: "커피", uzbek: "kofe" },
        { korean: "좀", uzbek: "iltimos" },
        { korean: "콜라", uzbek: "kola" },
        { korean: "주스", uzbek: "sharbat" },
        { korean: "교통카드", uzbek: "transport kartasi" },
        { korean: "휴지", uzbek: "salfetka" },
        { korean: "물", uzbek: "suv" },
        { korean: "어서 오세요", uzbek: "xush kelibsiz" },
        { korean: "사과", uzbek: "olma" },
        { korean: "오랜지", uzbek: "apelsin" },
        { korean: "영화", uzbek: "kino" },
        { korean: "우유", uzbek: "sut" },
        { korean: "바나나", uzbek: "banan" },
        { korean: "딸기", uzbek: "qulupnay" },
        { korean: "텔레비전", uzbek: "televizor" },
        { korean: "방", uzbek: "xona" },
        { korean: "서울대학교", uzbek: "Seul universiteti" },
        { korean: "제", uzbek: "mening" },
        { korean: "침대", uzbek: "kravat" },
        { korean: "룸메이트", uzbek: "xonadosh" },
        { korean: "에어컨", uzbek: "konditsioner" },
        { korean: "물건", uzbek: "narsa" },
        { korean: "팀", uzbek: "jamoa" },
        { korean: "나누다", uzbek: "bo'lishmoq" },
        { korean: "받다", uzbek: "olmoq" },
        { korean: "붙이다", uzbek: "yopishtirmoq" }
    ],
    [ // 3
        { korean: "자다", uzbek: "uxlamoq" },
        { korean: "공부하다", uzbek: "o'qimoq/o'rganmoq" },
        { korean: "일하다", uzbek: "ishlamoq" },
        { korean: "운동하다", uzbek: "sport bilan shug'ullanmoq" },
        { korean: "숙제를 하다", uzbek: "uy vazifa qilmoq" },
        { korean: "옷을 사다", uzbek: "kiyim sotib olmoq" },
        { korean: "영화를 보다", uzbek: "kino ko'rmoq" },
        { korean: "친구를 만나다", uzbek: "do'sti bilan uchrashmoq" },
        { korean: "태권도를 배우다", uzbek: "tekvando o'rganmoq" },
        { korean: "밥을 먹다", uzbek: "ovqat yemoq" },
        { korean: "커피를 마시다", uzbek: "kofe ichmoq" },
        { korean: "책을 읽다", uzbek: "kitob o'qimoq" },
        { korean: "도서관", uzbek: "kutubxona" },
        { korean: "집", uzbek: "uy" },
        { korean: "백화점", uzbek: "univermag" },
        { korean: "시장", uzbek: "bozor" },
        { korean: "공원", uzbek: "park/bog’" },
        { korean: "커피숍", uzbek: "kafe" },
        { korean: "극장", uzbek: "kinoteatr" },
        { korean: "학교", uzbek: "maktab" },
        { korean: "식당", uzbek: "oshxona" },
        { korean: "회사", uzbek: "firma" },
        { korean: "지금", uzbek: "hozir" },
        { korean: "하다", uzbek: "qilmoq" },
        { korean: "쉬다", uzbek: "dam olmoq" },
        { korean: "피자", uzbek: "pitsa" },
        { korean: "보다", uzbek: "ko'rmoq" },
        { korean: "사다", uzbek: "sotib olmoq" },
        { korean: "먹다", uzbek: "yemoq" },
        { korean: "마시다", uzbek: "ichmoq" },
        { korean: "읽다", uzbek: "o'qimoq" },
        { korean: "배우다", uzbek: "o'rganmoq" },
        { korean: "일본어", uzbek: "yapon tili" },
        { korean: "아르바이트하다", uzbek: "qo'shimcha ish qilmoq" },
        { korean: "요리", uzbek: "pishirish" },
        { korean: "만나다", uzbek: "uchrashmoq" },
        { korean: "오늘", uzbek: "bugun" },
        { korean: "그리고", uzbek: "va" },
        { korean: "어디", uzbek: "qayer" },
        { korean: "고기", uzbek: "go'sht" },
        { korean: "프랑스어", uzbek: "fransuz tili" },
        { korean: "드라마", uzbek: "serial/dorama" },
        { korean: "그럼", uzbek: "unday bo'lsa" },
        { korean: "스포츠 센터", uzbek: "sport markazi" },
        { korean: "차", uzbek: "choy" },
        { korean: "가르치다", uzbek: "o'qitmoq" },
        { korean: "언어교육원", uzbek: "til markazi" },
        { korean: "불고기", uzbek: "pulgogi" },
        { korean: "노래방", uzbek: "karaoke" }
    ],
    [ // 4
        { korean: "공항", uzbek: "aeroport" },
        { korean: "우체국", uzbek: "pochta" },
        { korean: "대사관", uzbek: "elchixona" },
        { korean: "은행", uzbek: "bank" },
        { korean: "가게", uzbek: "magazin" },
        { korean: "약국", uzbek: "apteka" },
        { korean: "병원", uzbek: "kasalxona" },
        { korean: "미용실", uzbek: "sartaroshxona" },
        { korean: "앞", uzbek: "oldi" },
        { korean: "뒤", uzbek: "orqasi" },
        { korean: "옆", uzbek: "yoni" },
        { korean: "안", uzbek: "ichi" },
        { korean: "아래/ 밑", uzbek: "osti/tagi" },
        { korean: "위", uzbek: "usti" },
        { korean: "인사동", uzbek: "Insadong" },
        { korean: "서울타워", uzbek: "Seul minorasi" },
        { korean: "명동", uzbek: "Myongdong" },
        { korean: "청계천", uzbek: "Chonkechon" },
        { korean: "대학로", uzbek: "Seuldagi attraksion" },
        { korean: "남산", uzbek: "Nam tog'i" },
        { korean: "교실", uzbek: "sinf xona" },
        { korean: "찻집", uzbek: "choyxona" },
        { korean: "서울", uzbek: "Seul" },
        { korean: "시내", uzbek: "shahar markazi" },
        { korean: "구경하다", uzbek: "tomosha qilmoq" },
        { korean: "쇼핑하다", uzbek: "xarid qilmoq" },
        { korean: "연극", uzbek: "teatr" },
        { korean: "알다", uzbek: "bilmoq" },
        { korean: "어머니", uzbek: "ona" },
        { korean: "아버지", uzbek: "ota" },
        { korean: "잘 지내다", uzbek: "ishlari yaxshi bo’lmoq" },
        { korean: "기숙사", uzbek: "yotoqxona" },
        { korean: "사진", uzbek: "rasm" },
        { korean: "매일", uzbek: "har kuni" },
        { korean: "그", uzbek: "u" },
        { korean: "반", uzbek: "sinf" },
        { korean: "사랑하다", uzbek: "sevmoq" },
        { korean: "서점", uzbek: "kitob do’koni" },
        { korean: "빵집", uzbek: "nonvoyxona" },
        { korean: "화장실", uzbek: "hojatxona" },
        { korean: "음식", uzbek: "ovqat/taom" },
        { korean: "기념품", uzbek: "suvenir" },
        { korean: "그림", uzbek: "rasm" }
    ],
    [ // 5
        { korean: "숫자", uzbek: "raqam, son" },
        { korean: "월요일", uzbek: "dushanba" },
        { korean: "화요일", uzbek: "seshanba" },
        { korean: "수요일", uzbek: "chorshanba" },
        { korean: "목요일", uzbek: "payshanba" },
        { korean: "금요일", uzbek: "juma" },
        { korean: "토요일", uzbek: "shanba" },
        { korean: "일요일", uzbek: "yakshanba" },
        { korean: "주말", uzbek: "hafta oxiri" },
        { korean: "날짜", uzbek: "sana" },
        { korean: "요일", uzbek: "hafta kuni" },
        { korean: "며칠", uzbek: "qaysi kun" },
        { korean: "시험", uzbek: "imtixon" },
        { korean: "언제", uzbek: "qachon" },
        { korean: "무슨", uzbek: "qaysi" },
        { korean: "생일", uzbek: "tug'ilgan kun" },
        { korean: "하고", uzbek: "bilan" },
        { korean: "크리스마스", uzbek: "Krismas" },
        { korean: "파티", uzbek: "bazm" },
        { korean: "시간", uzbek: "vaqt" },
        { korean: "미안하다", uzbek: "uzr so'ramoq" },
        { korean: "약속", uzbek: "uchrashuv/vada" },
        { korean: "같이", uzbek: "birga" },
        { korean: "어제", uzbek: "kecha" },
        { korean: "코엑스몰", uzbek: "Seuldagi savdo markazi" },
        { korean: "카드", uzbek: "karta" },
        { korean: "선물", uzbek: "sovg'a" },
        { korean: "세수하다", uzbek: "yuvinmoq" },
        { korean: "이를 닦다", uzbek: "tish yuvmoq" },
        { korean: "거기", uzbek: "u joy" },
        { korean: "산책하다", uzbek: "sayr qilmoq" },
        { korean: "사진을 찍다", uzbek: "rasm olmoq" },
        { korean: "누구", uzbek: "kim" },
        { korean: "혼자", uzbek: "yolg'iz" },
        { korean: "끝나다", uzbek: "tugamoq" },
        { korean: "강남역", uzbek: "Gangnam bekati" },
        { korean: "그래서", uzbek: "shuning uchun" },
        { korean: "내일", uzbek: "ertaga" },
        { korean: "스케줄", uzbek: "kun tartibi" },
        { korean: "지난주", uzbek: "o’tgan hafta" },
        { korean: "양력", uzbek: "quyosh kalendari" },
        { korean: "음력", uzbek: "oy kalendari" },
        { korean: "설날", uzbek: "yangi yil" },
        { korean: "세배를 하다", uzbek: "tazim qilmoq" },
        { korean: "떡국", uzbek: "tokkuk" },
        { korean: "추석", uzbek: "hosil bayrami/shukronalik kuni" },
        { korean: "차례를 지내다", uzbek: "marosim o'tkazmoq" },
        { korean: "송편", uzbek: "guruchli pishiriq" }
    ],
    [ // 6
        { korean: "샌드위치", uzbek: "sendvich" },
        { korean: "스파게티", uzbek: "spagetti" },
        { korean: "피자", uzbek: "pitsa" },
        { korean: "햄버거", uzbek: "gamburger" },
        { korean: "귤", uzbek: "mandarin" },
        { korean: "딸기", uzbek: "qulupnay" },
        { korean: "사과", uzbek: "olma" },
        { korean: "수박", uzbek: "tarvuz" },
        { korean: "앉다", uzbek: "o'tirmoq" },
        { korean: "주다", uzbek: "bermoq" },
        { korean: "잠깐만", uzbek: "biroz" },
        { korean: "기다리다", uzbek: "kutmoq" },
        { korean: "빵", uzbek: "non" },
        { korean: "몇", uzbek: "qancha/necha" },
        { korean: "아이스크림", uzbek: "muzqaymoq" },
        { korean: "주스", uzbek: "sharbat" },
        { korean: "녹차", uzbek: "ko'k choy" },
        { korean: "콜라", uzbek: "kola" },
        { korean: "메뉴", uzbek: "menyu" },
        { korean: "좋아하다", uzbek: "yaxshi ko'rmoq" },
        { korean: "우동", uzbek: "udon taomi" },
        { korean: "맥주", uzbek: "pivo" },
        { korean: "물건", uzbek: "narsa" },
        { korean: "게수", uzbek: "sanoq" },
        { korean: "그래요", uzbek: "shunday" },
        { korean: "여기요", uzbek: "kechirasiz (birovni chaqirganda)" },
        { korean: "맛있다", uzbek: "mazali" },
        { korean: "좋다", uzbek: "yaxshi" },
        { korean: "싸다", uzbek: "arzon" },
        { korean: "길", uzbek: "yo'l" },
        { korean: "복잡하다", uzbek: "tiqilinch" },
        { korean: "노래", uzbek: "qo'shiq" },
        { korean: "아리랑", uzbek: "koreya folkor musiqasi" },
        { korean: "바지", uzbek: "shim" },
        { korean: "운동화", uzbek: "krossovka" },
        { korean: "아저씨", uzbek: "amaki" },
        { korean: "모두", uzbek: "hammasi" },
        { korean: "또", uzbek: "yana" },
        { korean: "키위", uzbek: "kivi" },
        { korean: "파인애플", uzbek: "ananas" },
        { korean: "박스", uzbek: "quti" },
        { korean: "멜론", uzbek: "qovun" },
        { korean: "과자", uzbek: "pishiriq" },
        { korean: "달걀", uzbek: "tuxum" },
        { korean: "휴지", uzbek: "salfetka" },
        { korean: "케이크", uzbek: "tort" },
        { korean: "아이스커피", uzbek: "muzli kofe" },
        { korean: "에스프래소", uzbek: "espresso" },
        { korean: "돈가스", uzbek: "kotlet" },
        { korean: "점심", uzbek: "tushlik" },
        { korean: "급", uzbek: "daraja" },
        { korean: "물건", uzbek: "narsa" },
        { korean: "팔다", uzbek: "sotmoq" },
        { korean: "인지", uzbek: "inch (o'lchov birlik)" },
        { korean: "아주", uzbek: "juda" },
        { korean: "리모컨", uzbek: "pult" },
        { korean: "깨끗하다", uzbek: "toza" },
        { korean: "많다", uzbek: "ko'p" },
        { korean: "권", uzbek: "kitoblarga –ta" },
        { korean: "전화하다", uzbek: "telefon qilmoq" },
        { korean: "비싸다", uzbek: "qimmat" },
        { korean: "깎아 주다", uzbek: "arzon qilmoq" },
        { korean: "백김치", uzbek: "oq kimchi" },
        { korean: "깍두기", uzbek: "rediskali kimchi" },
        { korean: "오이김치", uzbek: "bodrng kimchi" },
        { korean: "물김치", uzbek: "suvli kimchi" },
        { korean: "이런", uzbek: "bunday" },
        { korean: "김치볶음밥", uzbek: "qovurilgan guruch" },
        { korean: "김치전", uzbek: "kimchi quymoq" },
        { korean: "얼마", uzbek: "qancha" },
        { korean: "십 원", uzbek: "10 von" },
        { korean: "오십 원", uzbek: "50 von" },
        { korean: "백 원", uzbek: "100 von" },
        { korean: "오백 원", uzbek: "500 von" },
        { korean: "천 원", uzbek: "1000 von" },
        { korean: "오천 원", uzbek: "5000 von" },
        { korean: "만 원", uzbek: "10.000 von" },
        { korean: "오만 원", uzbek: "50.000 von" }
    ],
    [ // 7
        { korean: "흐리다", uzbek: "bulutli" },
        { korean: "맑다", uzbek: "havo ochiq" },
        { korean: "덥다", uzbek: "issiq" },
        { korean: "춥다", uzbek: "sovuq" },
        { korean: "따뜻하다", uzbek: "iliq" },
        { korean: "시원하다", uzbek: "salqin" },
        { korean: "비가 오다", uzbek: "yomg'ir yog'moq" },
        { korean: "눈이 오다", uzbek: "qor yog’moq" },
        { korean: "계절", uzbek: "fasl" },
        { korean: "봄", uzbek: "bahor" },
        { korean: "여름", uzbek: "yoz" },
        { korean: "가을", uzbek: "kuz" },
        { korean: "겨울", uzbek: "qish" },
        { korean: "쉽다", uzbek: "oson" },
        { korean: "어렵다", uzbek: "qiyin" },
        { korean: "맵다", uzbek: "achchiq" },
        { korean: "가볍다", uzbek: "yengil" },
        { korean: "무겁다", uzbek: "og'ir" },
        { korean: "불규칙", uzbek: "qoidaga tushmaslik" },
        { korean: "날씨", uzbek: "ob havo" },
        { korean: "어때요?", uzbek: "Qanday?" },
        { korean: "재미있다", uzbek: "qiziqarli" },
        { korean: "동생", uzbek: "uka" },
        { korean: "떡붂이", uzbek: "tokpukki" },
        { korean: "재미없다", uzbek: "qiziq emas" },
        { korean: "도쿄", uzbek: "Tokyo" },
        { korean: "조심해서 오세요", uzbek: "ehtiyot bo’lib keling" },
        { korean: "런던", uzbek: "London" },
        { korean: "싱가포르", uzbek: "Singapur" },
        { korean: "모스크바", uzbek: "Moskva" },
        { korean: "카이로", uzbek: "Qohira" },
        { korean: "시드니", uzbek: "Sidney" },
        { korean: "뉴욕", uzbek: "Nyu York" },
        { korean: "베이징", uzbek: "Pekin" },
        { korean: "어떻다", uzbek: "qanday" },
        { korean: "파리", uzbek: "Parij" },
        { korean: "요즘", uzbek: "shu kunlarda" },
        { korean: "쉬는 시간", uzbek: "dam olish vaqti" },
        { korean: "이야기하다", uzbek: "suhbatlashmoq" },
        { korean: "고향", uzbek: "vatan" },
        { korean: "스키장", uzbek: "chang'i kompleksi" },
        { korean: "단풍", uzbek: "xazonrezgirlik" },
        { korean: "수영장", uzbek: "suzish kompleksi" },
        { korean: "꽃", uzbek: "gul" },
        { korean: "바다", uzbek: "dengiz" },
        { korean: "생선", uzbek: "baliqli taom" },
        { korean: "부산", uzbek: "Pusan" },
        { korean: "질문", uzbek: "savol" },
        { korean: "작년", uzbek: "o’tgan yili" },
        { korean: "브라질", uzbek: "Braziliya" },
        { korean: "에서", uzbek: "...dan" },
        { korean: "브라질리아", uzbek: "Brazilia" },
        { korean: "항상", uzbek: "doim" },
        { korean: "처음", uzbek: "ilk bor" },
        { korean: "하늘", uzbek: "osmon" },
        { korean: "눈사람", uzbek: "qor odam" },
        { korean: "만들다", uzbek: "tayyorlamoq" },
        { korean: "필요하다", uzbek: "zarur bo'moq" },
        { korean: "놓다", uzbek: "bepul bo'lish" },
        { korean: "각각", uzbek: "har bir" },
        { korean: "태국", uzbek: "Tailand" },
        { korean: "수영하다", uzbek: "suzmoq" },
        { korean: "망고", uzbek: "mango" },
        { korean: "선글라스", uzbek: "ko'zoynak (quyosh)" },
        { korean: "부채", uzbek: "fen" },
        { korean: "슬리퍼", uzbek: "shippak/tapochka" },
        { korean: "삼계탕", uzbek: "samketang" },
        { korean: "들", uzbek: "...lar" }
    ],
    [ // 8
        { korean: "골프", uzbek: "golf" },
        { korean: "자전거", uzbek: "velosiped" },
        { korean: "게임", uzbek: "o'yin" },
        { korean: "테니스", uzbek: "tennis" },
        { korean: "농구", uzbek: "basketbol" },
        { korean: "피아노", uzbek: "pianino" },
        { korean: "당구", uzbek: "billiard" },
        { korean: "스키", uzbek: "chang'i" },
        { korean: "기타", uzbek: "gitara" },
        { korean: "스케이트", uzbek: "skeyt" },
        { korean: "축구", uzbek: "futbol" },
        { korean: "치다", uzbek: "o'ynamoq, chalmoq" },
        { korean: "타다", uzbek: "minmoq/uchmoq" },
        { korean: "하다", uzbek: "qilmoq" },
        { korean: "낮잠을 자다", uzbek: "kunduzgi uyqu uxlamoq" },
        { korean: "등산을 하다", uzbek: "tog'ga chiqmoq" },
        { korean: "산책을 하다", uzbek: "sayr qilmoq" },
        { korean: "여행을 하다", uzbek: "sayohat qilmoq" },
        { korean: "노래방에 가다", uzbek: "karaokega bormoq" },
        { korean: "찜질바에 가다", uzbek: "saunaga bormoq" },
        { korean: "걷다", uzbek: "yurmoq" },
        { korean: "버스", uzbek: "avtobus" },
        { korean: "타다", uzbek: "minmoq" },
        { korean: "걸어서 가다", uzbek: "piyoda yurib bormoq" },
        { korean: "음악", uzbek: "musiqa" },
        { korean: "듣다", uzbek: "eshitmoq" },
        { korean: "뉴스", uzbek: "yangilik" },
        { korean: "라디오", uzbek: "radio" },
        { korean: "잘", uzbek: "yaxshi" },
        { korean: "생활", uzbek: "hayot" },
        { korean: "조금", uzbek: "biroz" },
        { korean: "심심하다", uzbek: "zerikarli" },
        { korean: "한강", uzbek: "Han daryosi" },
        { korean: "그런데", uzbek: "lekin" },
        { korean: "어떻게", uzbek: "qanday qilib" },
        { korean: "가깝다", uzbek: "yaqin" },
        { korean: "관악산", uzbek: "Gvanak tog’i" },
        { korean: "시청", uzbek: "shahar markazi" },
        { korean: "정말", uzbek: "haqiqatdan" },
        { korean: "많다", uzbek: "ko'p" },
        { korean: "자주", uzbek: "tez-tez" },
        { korean: "그래요", uzbek: "shunday/rostdan" },
        { korean: "다음", uzbek: "kelasi" },
        { korean: "피곤하다", uzbek: "charchamoq" },
        { korean: "크다", uzbek: "katta" },
        { korean: "식혜", uzbek: "guruchli ichimlik" },
        { korean: "저기", uzbek: "anavi yer" },
        { korean: "수업", uzbek: "dars" },
        { korean: "오후", uzbek: "tushdan so'ng" },
        { korean: "운동장", uzbek: "sport maydoni" },
        { korean: "번", uzbek: "nomer" },
        { korean: "보통", uzbek: "odatda" },
        { korean: "미팅", uzbek: "uchrashuv" },
        { korean: "소개하다", uzbek: "tanishtirmoq" },
        { korean: "소개팅", uzbek: "tanishuv uchrashuvi" },
        { korean: "웃어른", uzbek: "katta odam" },
        { korean: "선을 보다", uzbek: "sovchilar orqali uchrashmoq" }
    ],
]



VOCCN = [
    "1A => kirish", // 0
    "1A => 1 과 ", // 1
    "1A => 2 과 ", // 2
    "1A => 3 과 ", // 3
    "1A => 4 과 ", // 4
    "1A => 5 과 ", // 5
    "1A => 6 과 ", // 6
    "1A => 7 과 ", // 7
    "1A => 8 과 ", // 8
];